services:
  - type: web
    name: dianafit
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.2.0
      - key: NODE_ENV
        value: production
