@echo off
echo Starting DianaFit Backend...
cd /d "c:\Users\user\Desktop\DianaFit\backend"
echo Installing dependencies...
call npm install
echo Starting backend server on port 3001...
call npm start
